# -*- coding: utf-8 -*-
"""animated monte carlo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RUn_zOdqPYIr_s6mhnQvfyheFm8_Ofit
"""

pip install numpy matplotlib imageio-ffmpeg

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import imageio_ffmpeg


# =========================================================
# SETTINGS
# =========================================================

START_PRICE = 100
EXPECTED_RETURN = 0.08       # 8% annual expected return
VOLATILITY = 0.25            # 25% annual volatility

TRADING_DAYS = 252
YEARS = 1
NUM_SIMULATIONS = 100

FPS = 30

INTRO_SECONDS = 2
SIMULATION_SECONDS = 8
OUTRO_SECONDS = 2

np.random.seed(42)


# =========================================================
# CONNECT MATPLOTLIB TO FFMPEG
# =========================================================

plt.rcParams["animation.ffmpeg_path"] = imageio_ffmpeg.get_ffmpeg_exe()


# =========================================================
# MONTE CARLO SIMULATION
# =========================================================

dt = YEARS / TRADING_DAYS

paths = np.zeros((TRADING_DAYS + 1, NUM_SIMULATIONS))

paths[0] = START_PRICE


for t in range(1, TRADING_DAYS + 1):

    random_shocks = np.random.normal(
        0,
        1,
        NUM_SIMULATIONS
    )

    paths[t] = paths[t - 1] * np.exp(

        (EXPECTED_RETURN - 0.5 * VOLATILITY**2) * dt

        +

        VOLATILITY
        * np.sqrt(dt)
        * random_shocks
    )


# =========================================================
# VIDEO TIMING
# =========================================================

intro_frames = INTRO_SECONDS * FPS

simulation_frames = SIMULATION_SECONDS * FPS

outro_frames = OUTRO_SECONDS * FPS

total_frames = (
    intro_frames
    + simulation_frames
    + outro_frames
)


# =========================================================
# CREATE 9:16 INSTAGRAM CANVAS
# =========================================================

fig, ax = plt.subplots(
    figsize=(9, 16)
)

fig.patch.set_facecolor("#07111f")

ax.set_facecolor("#07111f")


# Leave room at the top and bottom for text
plt.subplots_adjust(
    top=0.75,
    bottom=0.18,
    left=0.15,
    right=0.95
)


# =========================================================
# AXIS STYLE
# =========================================================

ax.set_xlim(
    0,
    TRADING_DAYS
)

ax.set_ylim(
    paths.min() * 0.90,
    paths.max() * 1.10
)


ax.set_xlabel(
    "Trading Days",
    fontsize=18,
    color="white",
    labelpad=15
)

ax.set_ylabel(
    "Simulated Stock Price ($)",
    fontsize=18,
    color="white",
    labelpad=15
)


ax.tick_params(
    axis="both",
    colors="white",
    labelsize=13
)


for spine in ax.spines.values():
    spine.set_color("#718096")


ax.grid(
    alpha=0.15,
    linestyle="--"
)


# =========================================================
# CREATE SIMULATION LINES
# =========================================================

lines = []


for i in range(NUM_SIMULATIONS):

    line, = ax.plot(
        [],
        [],
        linewidth=1.2,
        alpha=0.28
    )

    lines.append(line)


# Starting price line

ax.axhline(
    START_PRICE,
    linestyle="--",
    linewidth=2,
    alpha=0.7
)


# =========================================================
# TEXT ELEMENTS
# =========================================================

main_title = fig.text(
    0.5,
    0.92,
    "MONTE CARLO",
    ha="center",
    va="center",
    fontsize=40,
    fontweight="bold",
    color="white"
)


subtitle = fig.text(
    0.5,
    0.875,
    "STOCK PRICE SIMULATION",
    ha="center",
    va="center",
    fontsize=23,
    fontweight="bold",
    color="#4ade80"
)


info_text = fig.text(
    0.5,
    0.81,
    (
        f"Starting Price: ${START_PRICE}   •   "
        f"Volatility: {VOLATILITY:.0%}\n"
        f"Horizon: {YEARS} Year   •   "
        f"Paths: {NUM_SIMULATIONS}"
    ),
    ha="center",
    va="center",
    fontsize=16,
    color="#cbd5e1",
    linespacing=1.8
)


counter_text = fig.text(
    0.5,
    0.105,
    "",
    ha="center",
    va="center",
    fontsize=22,
    fontweight="bold",
    color="white"
)


message_text = fig.text(
    0.5,
    0.055,
    "",
    ha="center",
    va="center",
    fontsize=17,
    color="#94a3b8"
)


# =========================================================
# INTRO TEXT
# =========================================================

intro_text = fig.text(
    0.5,
    0.48,
    "",
    ha="center",
    va="center",
    fontsize=31,
    fontweight="bold",
    color="white",
    multialignment="center"
)


# =========================================================
# ANIMATION FUNCTION
# =========================================================

def update(frame):

    # -----------------------------------------
    # INTRO
    # -----------------------------------------

    if frame < intro_frames:

        intro_progress = frame / intro_frames

        intro_text.set_text(
            "What could happen to a\n$100 stock over 1 year?"
        )

        intro_text.set_alpha(
            min(1, intro_progress * 3)
        )

        counter_text.set_text(
            "100 possible futures"
        )

        message_text.set_text(
            "Generated with Python"
        )


        for line in lines:
            line.set_data([], [])


    # -----------------------------------------
    # MAIN SIMULATION
    # -----------------------------------------

    elif frame < intro_frames + simulation_frames:

        intro_text.set_text("")

        simulation_frame = (
            frame - intro_frames
        )

        progress = (
            simulation_frame
            / simulation_frames
        )

        day = int(
            progress * TRADING_DAYS
        )

        day = min(
            day,
            TRADING_DAYS
        )


        for i, line in enumerate(lines):

            line.set_data(
                np.arange(day + 1),
                paths[:day + 1, i]
            )


        counter_text.set_text(
            f"Day {day} / {TRADING_DAYS}"
        )


        message_text.set_text(
            "Each line represents one possible future"
        )


    # -----------------------------------------
    # OUTRO
    # -----------------------------------------

    else:

        intro_text.set_text(
            "MONTE CARLO DOESN'T\nPREDICT ONE FUTURE"
        )

        intro_text.set_color(
            "#4ade80"
        )


        counter_text.set_text(
            "It models many possible futures."
        )


        message_text.set_text(
            "Simulation ≠ Prediction   •   Follow for Python + Finance"
        )


        for i, line in enumerate(lines):

            line.set_data(
                np.arange(TRADING_DAYS + 1),
                paths[:, i]
            )


    return (
        lines
        + [
            intro_text,
            counter_text,
            message_text
        ]
    )


# =========================================================
# CREATE ANIMATION
# =========================================================

ani = animation.FuncAnimation(
    fig,
    update,
    frames=total_frames,
    interval=1000 / FPS,
    blit=False
)


# =========================================================
# EXPORT MP4
# =========================================================

output_file = "/content/monte_carlo_instagram_reel.mp4"


writer = animation.FFMpegWriter(
    fps=FPS,
    bitrate=5000
)


ani.save(
    output_file,
    writer=writer,
    dpi=120
)


plt.close()


print()
print("======================================")
print("VIDEO CREATED SUCCESSFULLY!")
print("======================================")
print()
print(f"File: {output_file}")

from google.colab import files

files.download("/content/monte_carlo_instagram_reel.mp4")

